# -*- coding: utf-8 -*-
"""Calcular correntes das malhas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19n59JcLOP1r9UcqXkDuhq51tzd2nE9VT
"""

import numpy as np

N = 3
R = np.array([1, 2, 3, 4, 5, 6])
V = np.array([10, 20, 30])
RL = 7

# Inicializa a matriz A.
A = np.zeros((N, N))

# Inicializa o vetor b.
b = np.zeros(N)

# Percorrer as malhas.
for i in range(N):
    # Soma as resistências dos ramos que compõem a malha i.
    R_eq = 0
    for j in range(N):
        if i != j:
            R_eq += R[i * (N-1) + j]

    # Adiciona a equação da malha i à matriz A e ao vetor b.
    A[i, i] = R_eq
    for j in range(N):
        if i != j:
            A[i, j] = -R[i * (N-1) + j]
    b[i] = V[i] - RL

print(A)
print(b)